<!-- layout carousel -->
<?php $this->partial("shared/carousel"); ?>

<!-- layout banner index -->
<div class="banner-index">
	<div class="container">
		<div class="row">
			<div class="main-title text-center">
				<h2>Sản phẩm mới</h2>
				<p class="shop-now">
					<a href="<?php echo $this->url->get('frontend/collections/new') ?>">Xem thêm</a>
				</p>
			</div>
			<div id="owl-product-index2" class="owl-carousel owl-theme clearfix banner-list">
				<?php foreach ($products as $product) : ?>
				<div class="banner-item">
					<div class="img">
						<a href="<?= $this->url->get('frontend/products/show/'.$product->_id) ?>">
							<div class="img-show" style="background: url(<?php echo $this->url->get('img/product/'.$product->images[2]['link']) ?>) no-repeat;background-size: cover;background-position: center;" ></div>
						</a>
					</div>
					<div class="info">
						<h3><a href="<?= $this->url->get('frontend/products/show/'.$product->_id) ?>"><?= $product->title ?></a></h3>
						<div class="prices">
							<span><?= number_format($product->price['promo_price']) ?>₫</span>
						</div>
					</div>
				</div>
				<?php endforeach; ?>
			</div>
		</div>
	</div>
</div>

<!-- layout all items -->
<?php $this->partial("shared/all-items"); ?>

<!-- layout banner index -->
<?php $this->partial("shared/seller"); ?>

<!-- layout banner bottom -->
<?php $this->partial("shared/banner-bottom"); ?>



