<main class="wrapper main-content" role="main">
<div id="shopify-section-collection-template" class="shopify-section collection-template-section">
<nav class="breadcrumb" role="navigation" aria-label="breadcrumbs">
  <a href="#" title="Back to the frontpage">Home</a>
    <span class="divider" aria-hidden="true">›</span>
      <span>All Items</span>
</nav>
<div class="grid grid-border">
  <div class="grid-item">
    <header class="section-header">
      <h3 class="section-header--title">All Items</h3>
      <div class="section-header--right">
        <div class="form-horizontal">
          <label for="sortBy" class="small--hide">Sắp xếp theo</label>
          <select name="sortBy" id="sortBy">
            <option value="manual">Sản phẩm nổi bật</option>
            <option value="best-selling">Sản phẩm bán chạy</option>
            <option value="title-ascending">Tên, A-Z</option>
            <option value="title-descending">Tên, Z-A</option>
            <option value="price-ascending">Giá: Tăng dần</option>
            <option value="price-descending">Giá: Giảm dần</option>
            <option value="created-descending">Mới nhất</option>
            <option value="created-ascending">Cũ nhất</option>
          </select>
        </div>
      </div>
    </header>
    <div class="grid-uniform">
  <!-- ----------------------------------------------------- -->
    <div product-selector="743983448110" class="grid-item small--one-half medium--one-quarter large--one-quarter">
      <a href="#" class="product-grid-item">
        <div class="product-grid-image">
          <div class="product-grid-image--centered">
            <div id="productImageWrapper-2665772777518" class="lazyload__image-wrapper no-js" style="padding-top:150.0%;">
              <img id="" class="" alt="E18052 - Cặp bấm La Rachel Camellia Hairpin" data-srcset="" sizes="227px" srcset="//cdn.shopify.com/s/files/1/2517/8012/products/T18090_580x.jpg">
            </div>
            <noscript>
              <img src="//cdn.shopify.com/s/files/1/2517/8012/products/T18090_580x.jpg"
             alt="E18052 - Cặp bấm La Rachel Camellia Hairpin" style="opacity:1;">
            </noscript>
          </div>
        </div>
        <p>E18052 - Cặp bấm La Rachel Camellia Hairpin</p>
        <div class="product-item--price">
          <span class="h1 medium--left">
              <span class="visually-hidden">Regular price</span>
              <small aria-hidden="true">75.000₫</small>
              <span class="visually-hidden">75.000₫</span>
          </span>
        </div>
      </a>
    </div>
      <!-- ----------------------------------------------------- -->
    <div product-selector="743983448110" class="grid-item small--one-half medium--one-quarter large--one-quarter">
      <a href="#" class="product-grid-item">
        <div class="product-grid-image">
          <div class="product-grid-image--centered">
            <div id="productImageWrapper-2665772777518" class="lazyload__image-wrapper no-js" style="padding-top:150.0%;">
              <img id="" class="" alt="E18052 - Cặp bấm La Rachel Camellia Hairpin" data-srcset="" sizes="227px" srcset="//cdn.shopify.com/s/files/1/2517/8012/products/T18090_580x.jpg">
            </div>
            <noscript>
              <img src="//cdn.shopify.com/s/files/1/2517/8012/products/T18090_580x.jpg"
             alt="E18052 - Cặp bấm La Rachel Camellia Hairpin" style="opacity:1;">
            </noscript>
          </div>
        </div>
        <p>E18052 - Cặp bấm La Rachel Camellia Hairpin</p>
        <div class="product-item--price">
          <span class="h1 medium--left">
              <span class="visually-hidden">Regular price</span>
              <small aria-hidden="true">75.000₫</small>
              <span class="visually-hidden">75.000₫</span>
          </span>
        </div>
      </a>
    </div>
      <!-- ----------------------------------------------------- -->
    <div product-selector="743983448110" class="grid-item small--one-half medium--one-quarter large--one-quarter">
      <a href="#" class="product-grid-item">
        <div class="product-grid-image">
          <div class="product-grid-image--centered">
            <div id="productImageWrapper-2665772777518" class="lazyload__image-wrapper no-js" style="padding-top:150.0%;">
              <img id="" class="" alt="E18052 - Cặp bấm La Rachel Camellia Hairpin" data-srcset="" sizes="227px" srcset="//cdn.shopify.com/s/files/1/2517/8012/products/T18090_580x.jpg">
            </div>
            <noscript>
              <img src="//cdn.shopify.com/s/files/1/2517/8012/products/T18090_580x.jpg"
             alt="E18052 - Cặp bấm La Rachel Camellia Hairpin" style="opacity:1;">
            </noscript>
          </div>
        </div>
        <p>E18052 - Cặp bấm La Rachel Camellia Hairpin</p>
        <div class="product-item--price">
          <span class="h1 medium--left">
              <span class="visually-hidden">Regular price</span>
              <small aria-hidden="true">75.000₫</small>
              <span class="visually-hidden">75.000₫</span>
          </span>
        </div>
      </a>
    </div>
      <!-- ----------------------------------------------------- -->
    <div product-selector="743983448110" class="grid-item small--one-half medium--one-quarter large--one-quarter">
      <a href="#" class="product-grid-item">
        <div class="product-grid-image">
          <div class="product-grid-image--centered">
            <div id="productImageWrapper-2665772777518" class="lazyload__image-wrapper no-js" style="padding-top:150.0%;">
              <img id="" class="" alt="E18052 - Cặp bấm La Rachel Camellia Hairpin" data-srcset="" sizes="227px" srcset="//cdn.shopify.com/s/files/1/2517/8012/products/T18090_580x.jpg">
            </div>
            <noscript>
              <img src="//cdn.shopify.com/s/files/1/2517/8012/products/T18090_580x.jpg"
             alt="E18052 - Cặp bấm La Rachel Camellia Hairpin" style="opacity:1;">
            </noscript>
          </div>
        </div>
        <p>E18052 - Cặp bấm La Rachel Camellia Hairpin</p>
        <div class="product-item--price">
          <span class="h1 medium--left">
              <span class="visually-hidden">Regular price</span>
              <small aria-hidden="true">75.000₫</small>
              <span class="visually-hidden">75.000₫</span>
          </span>
        </div>
      </a>
    </div>
      <!-- ----------------------------------------------------- -->
    <div product-selector="743983448110" class="grid-item small--one-half medium--one-quarter large--one-quarter">
      <a href="#" class="product-grid-item">
        <div class="product-grid-image">
          <div class="product-grid-image--centered">
            <div id="productImageWrapper-2665772777518" class="lazyload__image-wrapper no-js" style="padding-top:150.0%;">
              <img id="" class="" alt="E18052 - Cặp bấm La Rachel Camellia Hairpin" data-srcset="" sizes="227px" srcset="//cdn.shopify.com/s/files/1/2517/8012/products/T18090_580x.jpg">
            </div>
            <noscript>
              <img src="//cdn.shopify.com/s/files/1/2517/8012/products/T18090_580x.jpg"
             alt="E18052 - Cặp bấm La Rachel Camellia Hairpin" style="opacity:1;">
            </noscript>
          </div>
        </div>
        <p>E18052 - Cặp bấm La Rachel Camellia Hairpin</p>
        <div class="product-item--price">
          <span class="h1 medium--left">
              <span class="visually-hidden">Regular price</span>
              <small aria-hidden="true">75.000₫</small>
              <span class="visually-hidden">75.000₫</span>
          </span>
        </div>
      </a>
    </div>
      <!-- ----------------------------------------------------- -->
    <div product-selector="743983448110" class="grid-item small--one-half medium--one-quarter large--one-quarter">
      <a href="#" class="product-grid-item">
        <div class="product-grid-image">
          <div class="product-grid-image--centered">
            <div id="productImageWrapper-2665772777518" class="lazyload__image-wrapper no-js" style="padding-top:150.0%;">
              <img id="" class="" alt="E18052 - Cặp bấm La Rachel Camellia Hairpin" data-srcset="" sizes="227px" srcset="//cdn.shopify.com/s/files/1/2517/8012/products/T18090_580x.jpg">
            </div>
            <noscript>
              <img src="//cdn.shopify.com/s/files/1/2517/8012/products/T18090_580x.jpg"
             alt="E18052 - Cặp bấm La Rachel Camellia Hairpin" style="opacity:1;">
            </noscript>
          </div>
        </div>
        <p>E18052 - Cặp bấm La Rachel Camellia Hairpin</p>
        <div class="product-item--price">
          <span class="h1 medium--left">
              <span class="visually-hidden">Regular price</span>
              <small aria-hidden="true">75.000₫</small>
              <span class="visually-hidden">75.000₫</span>
          </span>
        </div>
      </a>
    </div>
      <!-- ----------------------------------------------------- -->
    <div product-selector="743983448110" class="grid-item small--one-half medium--one-quarter large--one-quarter">
      <a href="#" class="product-grid-item">
        <div class="product-grid-image">
          <div class="product-grid-image--centered">
            <div id="productImageWrapper-2665772777518" class="lazyload__image-wrapper no-js" style="padding-top:150.0%;">
              <img id="" class="" alt="E18052 - Cặp bấm La Rachel Camellia Hairpin" data-srcset="" sizes="227px" srcset="//cdn.shopify.com/s/files/1/2517/8012/products/T18090_580x.jpg">
            </div>
            <noscript>
              <img src="//cdn.shopify.com/s/files/1/2517/8012/products/T18090_580x.jpg"
             alt="E18052 - Cặp bấm La Rachel Camellia Hairpin" style="opacity:1;">
            </noscript>
          </div>
        </div>
        <p>E18052 - Cặp bấm La Rachel Camellia Hairpin</p>
        <div class="product-item--price">
          <span class="h1 medium--left">
              <span class="visually-hidden">Regular price</span>
              <small aria-hidden="true">75.000₫</small>
              <span class="visually-hidden">75.000₫</span>
          </span>
        </div>
      </a>
    </div>
  <!-- ----------------------------------------------------- -->
    <div product-selector="743983448110" class="grid-item small--one-half medium--one-quarter large--one-quarter">
      <a href="#" class="product-grid-item">
        <div class="product-grid-image">
          <div class="product-grid-image--centered">
            <div id="productImageWrapper-2665772777518" class="lazyload__image-wrapper no-js" style="padding-top:150.0%;">
              <img id="" class="" alt="E18052 - Cặp bấm La Rachel Camellia Hairpin" data-srcset="" sizes="227px" srcset="//cdn.shopify.com/s/files/1/2517/8012/products/T18090_580x.jpg">
            </div>
            <noscript>
              <img src="//cdn.shopify.com/s/files/1/2517/8012/products/T18090_580x.jpg"
             alt="E18052 - Cặp bấm La Rachel Camellia Hairpin" style="opacity:1;">
            </noscript>
          </div>
        </div>
        <p>E18052 - Cặp bấm La Rachel Camellia Hairpin</p>
        <div class="product-item--price">
          <span class="h1 medium--left">
              <span class="visually-hidden">Regular price</span>
              <small aria-hidden="true">75.000₫</small>
              <span class="visually-hidden">75.000₫</span>
          </span>
        </div>
      </a>
    </div>
<!-- ----------------------------------------------------- -->
<div class="grid-item pagination-border-top">
  <div class="grid">
    <div class="grid-item">
      <div class="text-center">
        <ul class="pagination-custom">
          <li class="disabled"><span>←</span></li>
            <li class="active"><span>1</span></li>
            <li>
              <a href="/collections/all?page=2&amp;view=grid" title="">2</a>
            </li>
            <li>
              <a href="/collections/all?page=3&amp;view=grid" title="">3</a>
            </li>
            <li><span>…</span></li>
            <li>
              <a href="/collections/all?page=12&amp;view=grid" title="">12</a>
            </li>
            <li>
              <a href="/collections/all?page=2&amp;view=grid" title="Next »">→</a></li>
            </ul>
          </div>
      </div>
    </div>
  </div>
</div>
</div>
</main>