<div id="owl-index" class="owl-carousel owl-theme">
	<div class="item">
		<img src="<?= $this->url->get('img/slide/slideshow_1c79a.jpg') ?>" alt="slider 1" />
		<div class="slider-caption">
			<div class="slider-title" >
			</div>
			<div class="slider-des ">
			</div>
			<a href="collections/san-pham-moi" class="slider-btn">Xem Thêm</a>
		</div>
	</div>
	<div class="item">
		<img src="<?= $this->url->get('img/slide/slideshow_2c79a.jpg') ?>" alt="slider 2" />
		<div class="slider-caption">
			<div class="slider-title" >
			</div>
			<div class="slider-des ">
			</div>
			<a href="collections/san-pham-ban-chay.html" class="slider-btn">Xem Thêm</a>
		</div>
	</div>
	<div class="item">
		<img src="<?= $this->url->get('img/slide/slideshow_3c79a.jpg') ?>" alt="slider 3" />
		<div class="slider-caption">
			<div class="slider-title" >
			</div>
			<div class="slider-des ">
			</div>
			<a href="collections/san-pham-khuyen-mai" class="slider-btn">Xem Thêm</a>
		</div>
	</div>
</div>