<div class="best-seller">
	<div class="container">
		<div class="row">
			<div class="main-title text-center">
				<h2>Sản phẩm bán chạy</h2>
				<p class="shop-now">
					<a href="<?php echo $this->url->get('products/seller') ?>">Xem thêm</a>
				</p>
			</div>
			<div id="owl-product-index" class="owl-carousel owl-theme">
				<div class="item">
					<div class="product-item">
						<div class="img">
							<a href="products/thun-trang-tui-giay">
								<div class="img-show" style="background: url(<?php echo $this->url->get('img/product/32765146_1599944410127904_2634841854889164800_o_41f2bb12118a434d84461761056a3cd7_large.jpg') ?>) no-repeat;background-size: cover;background-position: center;" ></div>
							</a>
						</div>
						<div class="info">
							<h3><a href="products/thun-trang-tui-giay">Thun Trắng Túi Giấy</a></h3>
							<div class="prices">
								<span>350,000₫</span>
							</div>
						</div>
					</div>
				</div>
				<div class="item">
					<div class="product-item">
						<div class="img">
							<a href="products/quan-dui-s-soda-hoa-tiet.html">
								<div class="img-show" style="background: url(<?php echo $this->url->get('img/product/37110391_1680450415410636_6887274053942378496_o_large.jpg') ?>) no-repeat;background-size: cover;background-position: center;" ></div>
							</a>
						</div>
						<div class="info">
							<h3><a href="products/quan-dui-s-soda-hoa-tiet.html">Quần Đùi S.soda Họa Tiết</a></h3>
							<div class="prices">
								<span>320,000₫</span>
							</div>
						</div>
					</div>
				</div>
				<div class="item">
					<div class="product-item">
						<div class="img">
							<a href="products/balo-c-k-chu-bu.html">
								<div class="img-show" style="background: url(<?php echo $this->url->get('img/product/38218435_1706065312849146_239081832727969792_o_0b0afbdca5984081adbfe12a2a9feb85_large.jpg') ?>) no-repeat;background-size: cover;background-position: center;" ></div>
							</a>
						</div>
						<div class="info">
							<h3><a href="products/balo-c-k-chu-bu.html">Balo C.k Chữ Bự</a></h3>
							<div class="prices">
								<span>420,000₫</span>
							</div>
						</div>
					</div>
				</div>
				<div class="item">
					<div class="product-item">
						<div class="img">
							<a href="products/non-con-ech.html">
								<div class="img-show" style="background: url(<?php echo $this->url->get('img/product/38177034_1706065296182481_9107416754610503680_o_large.jpg') ?>) no-repeat;background-size: cover;background-position: center;" ></div>
							</a>
						</div>
						<div class="info">
							<h3><a href="products/non-con-ech.html">Nón Con Ếch</a></h3>
							<div class="prices">
								<span>250,000₫</span>
							</div>
						</div>
					</div>
				</div>
				<div class="item">
					<div class="product-item">
						<div class="img">
							<a href="products/ao-thun-v-ans-tui.html">
								<div class="img-show" style="background: url(<?php echo $this->url->get('img/product/38132241_1706021159520228_4924890229246001152_o_96f4b70249214791ae8fe41bbdeac673_large.jpg') ?>) no-repeat;background-size: cover;background-position: center;" ></div>
							</a>
						</div>
						<div class="info">
							<h3><a href="products/ao-thun-v-ans-tui.html">Áo Thun V.ans Túi</a></h3>
							<div class="prices">
								<span>270,000₫</span>
							</div>
						</div>
					</div>
				</div>
				<div class="item">
					<div class="product-item">
						<div class="img">
							<a href="products/quan-dai-zr-nut-suon.html">
								<div class="img-show" style="background: url(<?php echo $this->url->get('img/product/38024803_1706021202853557_1152831933063888896_o_large.jpg') ?>) no-repeat;background-size: cover;background-position: center;" ></div>
							</a>
						</div>
						<div class="info">
							<h3><a href="products/quan-dai-zr-nut-suon.html">Quần Dài ZR Nút Sườn</a></h3>
							<div class="prices">
								<span>350,000₫</span>
							</div>
						</div>
					</div>
				</div>
				<div class="item">
					<div class="product-item">
						<div class="img">
							<a href="products/so-mi-inf-soc-3-mau.html">
								<div class="img-show" style="background: url(<?php echo $this->url->get('img/product/36654596_1666732160115795_4108160072872361984_o_large.jpg') ?>) no-repeat;background-size: cover;background-position: center;" ></div>
							</a>
						</div>
						<div class="info">
							<h3><a href="products/so-mi-inf-soc-3-mau.html">Sơ Mi INF Sọc 3 Màu</a></h3>
							<div class="prices">
								<span>280,000₫</span>
							</div>
						</div>
					</div>
				</div>
				<div class="item">
					<div class="product-item">
						<div class="img">
							<a href="products/jogger-j-ordan.html">
								<div class="img-show" style="background: url(<?php echo $this->url->get('img/product/37928854_1702862173169460_8236717898916167680_o_large.jpg') ?>) no-repeat;background-size: cover;background-position: center;" ></div>
							</a>
						</div>
						<div class="info">
							<h3><a href="products/jogger-j-ordan.html">Jogger J.ordan</a></h3>
							<div class="prices">
								<span>350,000₫</span>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>