<div class="content-wrapper">
  <div class="row">
    <div class="col-12 grid-margin">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title" style="float: left;"><b>Thêm mới sản phẩm</b></h4>
          <a href="<?= $this->url->get('backend/products') ?>" class="btn btn-success btn-fw mdi mdi-view-list" style="float: right; color: white"> Danh sách</a><br>
          <hr>
          <form class="form-sample" method="post" enctype="multipart/form-data">
            <p class="card-description">
              Thông tin sản phẩm
            </p>
            <div class="row">
              <div class="col-md-6">
                <div class="form-group row">
                  <label class="col-sm-3 col-form-label">Tên sản phẩm</label>
                  <div class="col-sm-9">
                    <input type="text" class="form-control" required name="title" value="" />
                  </div>
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group row">
                  <label class="col-sm-3 col-form-label">Danh mục</label>
                  <div class="col-sm-9">
                    <select class="form-control" name="category">
                      <?php foreach ($categories as $category) : ?>

                        <!-- kiểm tra nếu là danh mục cha -->
                        <?php if (is_null($category->parent_id)) :?>
                          <option value="<?= $category->_id ?>" disabled style="font-weight: bold"><?= ucfirst($category->_id) ?></option>
                        <?php endif; ?>

                        <!-- duyệt danh mục con -->
                        <?php foreach ($categories as $key) : ?>
                          <?php if ($key->parent_id == $category->_id) :?>
                            <option value="<?= $key->_id ?>"><?= ucfirst($key->_id) ?></option>
                          <?php endif; ?>
                        <?php endforeach; ?>

                      <?php endforeach; ?>
                    </select>
                  </div>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6">
                <div class="form-group row">
                  <label class="col-sm-3 col-form-label">Giá nhập</label>
                  <div class="col-sm-9">
                    <input type="text" class="form-control" required name="in_price" value="" />
                    <?php if (isset($errors['in_price'])): ?>
                      <div class="errors"><?= $errors['in_price'] ?></div>
                    <?php endif; ?>
                  </div>
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group row">
                  <label class="col-sm-3 col-form-label">Giá bán</label>
                  <div class="col-sm-9">
                    <input type="text" class="form-control" required name="sale_price" value="" />
                    <?php if (isset($errors['sale_price'])): ?>
                      <div class="errors"><?= $errors['sale_price'] ?></div>
                    <?php endif; ?>
                  </div>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6">
                <div class="form-group row">
                  <label class="col-sm-3 col-form-label">(%) Khuyến mãi</label>
                  <div class="col-sm-9">
                    <input type="text" class="form-control" required name="promo_price" value="" />
                    <?php if (isset($errors['promo_price'])): ?>
                      <div class="errors"><?= $errors['promo_price'] ?></div>
                    <?php endif; ?>
                  </div>
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group row">
                  <label class="col-sm-3 col-form-label">Số lượng</label>
                  <div class="col-sm-9">
                    <input type="text" class="form-control" required name="total" value="" />
                    <?php if (isset($errors['total'])): ?>
                      <div class="errors"><?= $errors['total'] ?></div>
                    <?php endif; ?>
                  </div>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6">
                <div class="form-group row">
                  <label class="col-sm-3 col-form-label">Hình ảnh</label>
                  <div class="col-sm-9">
                    <input type="file" class="form-control" name="images" required placeholder="">
                    <?php if (isset($errors['images'])): ?>
                      <div class="errors"><?= $errors['images'] ?></div>
                    <?php endif; ?>
                  </div>
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group row">
                  <label class="col-sm-3 col-form-label">Mô tả</label>
                  <div class="col-sm-9">
                    <input type="text" class="form-control" required name="desc" value="" />
                  </div>
                </div>
              </div>
            </div>
            <button class="btn btn-primary" style="color: white">Thêm mới</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- content-wrapper ends -->