<div class="col-lg-12 grid-margin stretch-card">
  <div class="card">
    <div class="card-body">
      <?php $this->flashSession->output() ?>
      <h4 class="card-title" style="float: left;">Quản lý sản phẩm</h4>
      <a href="<?= $this->url->get('backend/products/add') ?>" class="btn btn-success btn-fw mdi mdi-database-plus" style="float: right; color: white"> Tạo mới</a><br>
      <p class="card-description"><hr></p>
      <div class="table-outter-wrapper">
        <table class="table table-hover table-bordered">
          <thead>
            <tr>
              <th>STT</th>
              <th>Tên</th>
              <th>Danh mục</th>
              <th>Giá bán</th>
              <th>Số lượng</th>
              <th>Hình ảnh</th>
              <th>Chi tiết</th>
              <th>Ngày tạo</th>
              <th>Ngày update</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            <?php $count = 1; foreach ($products as $product): ?>
            <tr>
              <td><?= $count ?></td>
              <td><?= $product->title ?></td>
              <td><?= $product->category ?></td>
              <td>
                <div style="text-decoration: line-through;">
                  <?= $product->price['in_price'] ?> &#273</div><br>
                <div style="text-decoration: line-through;">
                  <?= $product->price['sale_price'] ?> &#273
                </div><br>
                <div style="color: red"><?= $product->price['promo_price'] ?> &#273</div> 
              </td>
              <td><?= $product->total ?></td>
              <td><img src="<?= $this->url->get('img/test/'.$product->images) ?>" alt=""></td>
              <td><?= $product->info ?></td>
              <td><?= Date("d/m/Y", $product->created_at) ?></td>
              <td><?= Date("d/m/Y", $product->updated_at) ?></td>
              <td style="font-size: 20px">
                <a href="<?= $this->url->get('backend/products/update/'.$product->_id) ?>" class="mdi mdi-pencil" title="Update"></a>
                <a href="<?= $this->url->get('backend/products/delete/'.$product->_id) ?>" class="mdi mdi-delete" title="Delete" onclick="return confirm('Bạn có chắc muốn xóa?')"></a>
              </td>
            </tr>
          <?php $count += 1; endforeach;?>
          </tbody>
        </table>
    </div>
    </div>
  </div>
</div>