<?php  ?>
<div class="col-lg-12 grid-margin stretch-card">
  <div class="card">
      <div class="card-body">
      <?php $this->flashSession->output() ?>
      <h4 class="card-title" style="float: left;">Quản lý đơn hàng</h4><br>
      <p class="card-description"><hr></p>
      <div class="table-outter-wrapper">
        <table class="table table-hover table-bordered">
          <thead>
            <tr>
              <th>STT</th>
              <th>Khách hàng</th>
              <th>Điện thoại</th>
              <th>Trị giá</th>
              <th>Ngày đặt</th>
              <th>Trạng thái</th>
              <th>Chi tiết</th>
            </tr>
          </thead>
          <tbody>
            <?php $count = 1; foreach ($orders as $value): ?>
            <?php $status = $value->status ?>
            <tr>
              <td><?= $count ?></td>
              <td><?= $value->customer_name ?></td>
              <td><?= $value->customer_phone ?></td>
              <td><?= number_format($value->total_price) ?> <u>&#273</u></div></td>
              <td><?= Date("d/m/Y", $value->created_at) ?></td>
              <?php switch ($status) {
                case 'Mới':
                  echo '<td><label class="badge badge-warning">'.$status.'</label></td>';
                  break;
                case 'Đã xác nhận':
                  echo '<td><label class="badge badge-danger">'.$status.'</label></td>';
                  break;
                case 'Đang giao':
                  echo '<td><label class="badge badge-info">'.$ostatus.'</label></td>';
                  break;
                case 'Hoàn thành':
                  echo '<td><label class="badge badge-success">'.$status.'</label></td>';
                  break;
                default:
                  break;
              } ?>
              <td style="font-size: 20px">
                <a href="<?= $this->url->get('backend/orders/details/'.$value->_id) ?>" class="mdi mdi-details" title="Chi tiết"></a>
                <a href="<?= $this->url->get('backend/orders/destroy/'.$value->_id) ?>" class="mdi mdi-delete" title="Destroy" onclick="return confirm('Bạn chắc muốn hủy đơn hàng này?')"></a>
              </td>
            </tr>
          <?php $count += 1; endforeach;?>
          </tbody>
        </table>
      </div>
	  </div>
  </div>
</div>