<div class="page pb30">
	<div class="fix-breadcrumb " >
	<ol class="breadcrumb breadcrumb-arrow hidden-sm hidden-xs">
		<li><a href="<?= $this->url->get('') ?>" target="_self">Trang chủ</a></li>
		<li class="active"><span>Hệ thống cửa hàng</span></li>
	</ol>
	</div>
		<div class="container">
			<div class="stores row">
				<div class="main-title2 text-center">
					<h1>Hệ thống cửa hàng</h1>
				</div>
				<div class="stores-list clearfix">
					<div class="stores-item">
						<a href="/blogs/diem-ban-binh-thanh/17bis">
							<img src="<?php echo $this->url->get('img/14/page_store_1.jpg') ?>" alt="Store 1" />
							<div class="stores-info">
								<p class="title">Store 1</p>
							<p class="address">17 Bis Huỳnh Đình Hai P.14 Quận Bình Thạnh</p>
							<p class="hotline">0909 045 600</p>
						</div>
					</a>
				</div>
				<div class="stores-item">
					<a href="/blogs/diem-ban-binh-thanh/32b-nguyen-bieu-phuong-1-quan-5">
						<img src="<?php echo $this->url->get('img/14/page_store_2.jpg') ?>" alt="Store 2" />
						<div class="stores-info">
							<p class="title">Store 2</p>
							<p class="address">332 Cao Đạt P.1 Quận 5</p>
							<p class="hotline">01634 100 200</p>
						</div>
					</a>
				</div>
				<div class="stores-item">
					<a href="/blogs/diem-ban-binh-thanh/188-16-thanh-thai-phuong-12-quan-10">
						<img src="<?php echo $this->url->get('img/14/page_store_3.jpg') ?>" alt="Store 3" />
						<div class="stores-info">
							<p class="title">Store 3</p>
							<p class="address">188/16 Thành Thái P.12 Quận 10</p>
							<p class="hotline">01667 131 234</p>
						</div>
					</a>
				</div>
			</div>
		</div>
	</div>
	<div class="stores-description">
		<div class="container">
			<div class="content">
				<p><strong>SOMEHOW STORE: A FASHION INDUSTRY LEGEND</strong></p><p><span style="font-size: 12pt;" data-mce-style="font-size: 12pt;"><em>Bằng cách nào đó</em><span>&nbsp;</span>--- Chúng tôi luôn cố gắng mang những sản phẩm thời trang dành cho nam với tính thẩm mĩ bắt kịp<span>&nbsp;</span><strong>xu hướng nhanh nhất, chất lượng hàng hóa tốt nhất</strong>.&nbsp;</span><span style="font-size: 12pt;" data-mce-style="font-size: 12pt;">Chúng tôi luôn đảm bảo từng sản phẩm được trưng bày và bán ở SomeHow Store đều đã được anh em chúng tôi trải nghiệm, và kiểm tra rất kĩ về chất lượng cũng như mẫu mã.</span><span class="text_exposed_show"><br><span style="font-size: 12pt;" data-mce-style="font-size: 12pt;">Cung cấp những thương hiệu chính hãng dành cho Nam:<span>&nbsp;</span><strong>INF, Bensteven, R.A.W, Icoin&amp;Denim</strong>,.....</span><br></span></p>
			</div>
		</div>
	</div>
</div>