<div id="collection">
	<!-- Begin collection info -->
	<!-- Content-->
	<div class="fix-breadcrumb " >
	<ol class="breadcrumb breadcrumb-arrow hidden-sm hidden-xs">
		<li><a href="../index.html" target="_self">Trang chủ</a></li>
		<li class="active"><span>Tất cả sản phẩm</span></li>
	</ol>
	<div class="container">
		<div class="row">
			<div class="clearfix filter-box">
				<div class="browse-tags pull-left">
					<span class="hidden">Sắp xếp theo:</span>
					<span  class="custom-dropdown custom-dropdown--white">
						<select class="sort-by custom-dropdown__select custom-dropdown__select--white">
							<option value="price-ascending">Giá: Tăng dần</option>
							<option value="price-descending">Giá: Giảm dần</option>
							<option value="title-ascending">Tên: A-Z</option>
							<option value="title-descending">Tên: Z-A</option>
							<option value="created-ascending">Cũ nhất</option>
							<option value="created-descending">Mới nhất</option>
							<option value="best-selling">Bán chạy nhất</option>
						</select>
					</span>
				</div>
				<div class="product-filter pull-left">
					<span class="filter-title">Lọc theo <i class="fa fa-angle-down"></i></span>
					<div class="filter-container">
						<div class="clearfix">
						</div>
						<div class="filter-btn text-right">
							<a href="javascript:void(0)">Tìm kiếm</a>
						</div>
					</div>
				</div>
				<div class="pull-right showing">
					Hiển thị 48/511 Sản phẩm
				</div>
			</div>
			<div class="product-lists clearfix">
			<div class="product-item">
				<div class="img">
					<a href="../products/ao-thun-t-my-co-tim.html">
						<div class="img-show" style="background: url(<?php echo $this->url->get('img/product/37284687_1685110501611294_7871138524722888704_o_large.jpg') ?>) no-repeat;background-size: cover;background-position: center;" ></div>
					</a>
				</div>
				<div class="info">
					<h3><a href="../products/ao-thun-t-my-co-tim.html">Áo Thun T.My Cổ Tim</a></h3>
					<div class="prices">
						<span>150,000₫</span>
						
					</div>
				</div>
			</div>
			<div class="product-item">
				<div class="img">
					<a href="../products/ao-khoac-zr-da-lon.html">
						<div class="img-show" style="background: url(<?php echo $this->url->get('img/product/37221747_1680403738748637_2614838255161442304_n_6a13ab5333c74e8fbfc92dc407b49fec_large.jpg') ?>) no-repeat;background-size: cover;background-position: center;" ></div>
					</a>
				</div>
				<div class="info">
					<h3><a href="../products/ao-khoac-zr-da-lon.html">Áo Khoác ZR Da lộn</a></h3>
					<div class="prices">
						<span>400,000₫</span>
						
					</div>
				</div>
			</div>
			<div class="product-item">
				<div class="img">
					<a href="../products/khoac-ni-ke-trang-den.html">
						<div class="img-show" style="background: url(<?php echo $this->url->get('img/product/37261552_1682133175242360_1836068011887296512_o_6a7937c48ef142b48eb000c3d071edf6_large.jpg') ?>) no-repeat;background-size: cover;background-position: center;" ></div>
					</a>
				</div>
				<div class="info">
					<h3><a href="../products/khoac-ni-ke-trang-den.html">Khoác Ni.Ke Trằng Đen</a></h3>
					<div class="prices">
						<span>450,000₫</span>
						
					</div>
				</div>
			</div>
			<div class="product-item">
				<div class="img">
					<a href="../products/p-lo-s-dry-5-mau.html">
						<div class="img-show" style="background: url(<?php echo $this->url->get('img/product/37871027_1698019756987035_1082138205890805760_o_2beaaee2688a406c91ff6655f73bfd5e_large.jpg') ?>) no-repeat;background-size: cover;background-position: center;" ></div>
					</a>
				</div>
				<div class="info">
					<h3><a href="../products/p-lo-s-dry-5-mau.html">P.Lo S.Dry 5 Màu</a></h3>
					<div class="prices">
						<span>300,000₫</span>
						
					</div>
				</div>
			</div>
			<div class="product-item">
				<div class="img">
					<a href="../products/thun-e-su-4m.html">
						<div class="img-show" style="background: url(<?php echo $this->url->get('img/product/37167546_1677308259058185_9221977555463045120_o_bb3fee9ed16646e08633a2d54aa448f4_large.jpg') ?>) no-repeat;background-size: cover;background-position: center;" ></div>
					</a>
				</div>
				<div class="info">
					<h3><a href="../products/thun-e-su-4m.html">Thun E.su 4M</a></h3>
					<div class="prices">
						<span>320,000₫</span>
						
					</div>
				</div>
			</div>
			<div class="product-item">
				<div class="img">
					<a href="../products/non-chu-b.html">
						<div class="img-show" style="background: url(<?php echo $this->url->get('img/product/37314971_1683490991773245_1487059051018715136_o_ee56789c42ef4808b658594962ede502_large.jpg') ?>) no-repeat;background-size: cover;background-position: center;" ></div>
					</a>
				</div>
				<div class="info">
					<h3><a href="../products/non-chu-b.html">Nón Chữ B</a></h3>
					<div class="prices">
						<span>250,000₫</span>
						
					</div>
				</div>
			</div>
			<div class="product-item">
				<div class="img">
					<a href="../products/non-con-ech.html">
						<div class="img-show" style="background: url(<?php echo $this->url->get('img/product/38177034_1706065296182481_9107416754610503680_o_large.jpg') ?>) no-repeat;background-size: cover;background-position: center;" ></div>
					</a>
				</div>
				<div class="info">
					<h3><a href="../products/non-con-ech.html">Nón Con Ếch</a></h3>
					<div class="prices">
						<span>250,000₫</span>
						
					</div>
				</div>
			</div>
			<div class="product-item">
				<div class="img">
					<a href="../products/dui-thun-l-cos.html">
						<div class="img-show" style="background: url(<?php echo $this->url->get('img/product/37245588_1680531125402565_2292259127168073728_o_d633f77c0686411e90a215808a077648_large.jpg') ?>) no-repeat;background-size: cover;background-position: center;" ></div>
					</a>
				</div>
				<div class="info">
					<h3><a href="../products/dui-thun-l-cos.html">Đùi Thun L.cos</a></h3>
					<div class="prices">
						<span>200,000₫</span>
						
					</div>
				</div>
			</div>
			<div class="product-item">
				<div class="img">
					<a href="../products/quan-jean-z-ra-xanh-xuoc-1.html">
						<div class="img-show" style="background: url(<?php echo $this->url->get('img/product/37650608_1691542794301398_2683702485180219392_o_large.jpg') ?>) no-repeat;background-size: cover;background-position: center;" ></div>
					</a>
				</div>
				<div class="info">
					<h3><a href="../products/quan-jean-z-ra-xanh-xuoc-1.html">Quần Jean Z.Ra Xanh Xược</a></h3>
					<div class="prices">
						<span>500,000₫</span>
						
					</div>
				</div>
			</div>
			<div class="product-item">
				<div class="img">
					<a href="../products/quan-jean-p-bear-den-xuoc.html">
						<div class="img-show" style="background: url(<?php echo $this->url->get('img/product/37314971_1683490991773245_1487059051018715136_o_f573d6bcf159454fa2c038b6f284e727_large.jpg') ?>) no-repeat;background-size: cover;background-position: center;" ></div>
					</a>
				</div>
				<div class="info">
					<h3><a href="../products/quan-jean-p-bear-den-xuoc.html">Quần Jean P.Bear Đen Xược</a></h3>
					<div class="prices">
						<span>500,000₫</span>
						
					</div>
				</div>
			</div>
			<div class="product-item">
				<div class="img">
					<a href="../products/ao-thun-n-balance-4-mau.html">
						<div class="img-show" style="background: url(<?php echo $this->url->get('img/product/37167546_1677308259058185_9221977555463045120_o_8d63352a5de34c5aa0e4bfd099b6b12a_large.jpg') ?>) no-repeat;background-size: cover;background-position: center;" ></div>
					</a>
				</div>
				<div class="info">
					<h3><a href="../products/ao-thun-n-balance-4-mau.html">Áo Thun N.Balance 4 Màu</a></h3>
					<div class="prices">
						<span>280,000₫</span>
						
					</div>
				</div>
			</div>
			<div class="product-item">
				<div class="img">
					<a href="../products/quan-kaki-l-vis-4m.html">
						<div class="img-show" style="background: url(<?php echo $this->url->get('img/product/37392855_1683551905100487_8432101497424052224_o_b7002fa160a24b67984ace71c9269e80_large.jpg') ?>) no-repeat;background-size: cover;background-position: center;" ></div>
					</a>
				</div>
				<div class="info">
					<h3><a href="../products/quan-kaki-l-vis-4m.html">Quần Kaki L.vis 4M</a></h3>
					<div class="prices">
						<span>400,000₫</span>
						
					</div>
				</div>
			</div>
			<div class="product-item">
				<div class="img">
					<a href="../products/thun-d-sel-chu.html">
						<div class="img-show" style="background: url(<?php echo $this->url->get('img/product/37084429_1675822245873453_752284532874412032_o_7996f1a6472145d9b315e3a943f1ea22_large.jpg') ?>) no-repeat;background-size: cover;background-position: center;" ></div>
					</a>
				</div>
				<div class="info">
					<h3><a href="../products/thun-d-sel-chu.html">Thun D.Sel Chữ</a></h3>
					<div class="prices">
						<span>320,000₫</span>
						
					</div>
				</div>
			</div>
			<div class="product-item">
				<div class="img">
					<a href="../products/non-camo-z-ra.html">
						<div class="img-show" style="background: url(<?php echo $this->url->get('img/product/36992534_1677274719061539_1945512274034688000_o_large.jpg') ?>) no-repeat;background-size: cover;background-position: center;" ></div>
					</a>
				</div>
				<div class="info">
					<h3><a href="../products/non-camo-z-ra.html">Nón Camo Z.RA</a></h3>
					<div class="prices">
						<span>230,000₫</span>
						
					</div>
				</div>
			</div>
			<div class="product-item">
				<div class="img">
					<a href="../products/thun-prps-2-mau-xanh-cam-vay-son.html">
						<div class="img-show" style="background: url(<?php echo $this->url->get('img/product/36603261_1660557957399882_4416906966631186432_o_large.jpg') ?>) no-repeat;background-size: cover;background-position: center;" ></div>
					</a>
				</div>
				<div class="info">
					<h3><a href="../products/thun-prps-2-mau-xanh-cam-vay-son.html">Thun PRPS 2 Màu Xanh Cam Vảy Sơn</a></h3>
					<div class="prices">
						<span>320,000₫</span>
						
					</div>
				</div>
			</div>
			<div class="product-item">
				<div class="img">
					<a href="../products/p-lo-t-my-5-mau-tron.html">
						<div class="img-show" style="background: url(<?php echo $this->url->get('img/product/37103306_1680443228744688_705306945094942720_o_large.jpg') ?>) no-repeat;background-size: cover;background-position: center;" ></div>
					</a>
				</div>
				<div class="info">
					<h3><a href="../products/p-lo-t-my-5-mau-tron.html">P.Lo T.My 5 Màu Trơn</a></h3>
					<div class="prices">
						<span>280,000₫</span>
						
					</div>
				</div>
			</div>
			<div class="product-item">
				<div class="img">
					<a href="../products/quan-jean-icon-chi-vang-chi-den.html">
						<div class="img-show" style="background: url(<?php echo $this->url->get('img/product/36907558_1669779796477698_7053011567675179008_n_9e4060d41f144186abc878de5603016a_large.jpg') ?>) no-repeat;background-size: cover;background-position: center;" ></div>
					</a>
				</div>
				<div class="info">
					<h3><a href="../products/quan-jean-icon-chi-vang-chi-den.html">Quần Jean ICon Chỉ Vàng- Chỉ Đen</a></h3>
					<div class="prices">
						<span>550,000₫</span>
						
					</div>
				</div>
			</div>
			<div class="product-item">
				<div class="img">
					<a href="../products/so-mi-raw-denim.html">
						<div class="img-show" style="background: url(<?php echo $this->url->get('img/product/36826309_1668284879960523_7641872968598945792_n_cad9b7e9728e4f03a38e0737ed38ecfc_large.jpg') ?>) no-repeat;background-size: cover;background-position: center;" ></div>
					</a>
				</div>
				<div class="info">
					<h3><a href="../products/so-mi-raw-denim.html">Sơ Mi Raw&denim</a></h3>
					<div class="prices">
						<span>350,000₫</span>
						
					</div>
				</div>
			</div>
			<div class="product-item">
				<div class="img">
					<a href="../products/ao-thun-icon-hinh.html">
						<div class="img-show" style="background: url(<?php echo $this->url->get('img/product/36815026_1669932706462407_7568100419889528832_n_large.jpg') ?>) no-repeat;background-size: cover;background-position: center;" ></div>
					</a>
				</div>
				<div class="info">
					<h3><a href="../products/ao-thun-icon-hinh.html">Áo thun Icon Hình</a></h3>
					<div class="prices">
						<span>250,000₫</span>
						
					</div>
				</div>
			</div>
			<div class="product-item">
				<div class="img">
					<a href="../products/ao-thun-d-a-s-caro-vai.html">
						<div class="img-show" style="background: url(<?php echo $this->url->get('img/product/36925721_1677314632390881_4033744000623050752_o_large.jpg') ?>) no-repeat;background-size: cover;background-position: center;" ></div>
					</a>
				</div>
				<div class="info">
					<h3><a href="../products/ao-thun-d-a-s-caro-vai.html">Áo Thun D.A.S Caro Vai</a></h3>
					<div class="prices">
						<span>250,000₫</span>
						
					</div>
				</div>
			</div>
			<div class="product-item">
				<div class="img">
					<a href="../products/vo-ae">
						<div class="img-show" style="background: url(<?php echo $this->url->get('img/product/36988165_1672858556169822_4666490011577745408_n_large.jpg') ?>) no-repeat;background-size: cover;background-position: center;" ></div>
					</a>
				</div>
				<div class="info">
					<h3><a href="../products/vo-ae">Vớ AE</a></h3>
					<div class="prices">
						<span>90,000₫</span>
						
					</div>
				</div>
			</div>
			<div class="product-item">
				<div class="img">
					<a href="../products/qua-n-tay-z-ra-3m.html">
						<div class="img-show" style="background: url(<?php echo $this->url->get('img/product/36950643_1672870136168664_1071126777327255552_o_d0e9cb57423f40139c0a74399cad2fac_large.jpg') ?>) no-repeat;background-size: cover;background-position: center;" ></div>
					</a>
				</div>
				<div class="info">
					<h3><a href="../products/qua-n-tay-z-ra-3m.html">Quần Tây Z.ra 3M</a></h3>
					<div class="prices">
						<span>350,000₫</span>
						
					</div>
				</div>
			</div>
			<div class="product-item">
				<div class="img">
					<a href="../products/giay-z-ra-trang.html">
						<div class="img-show" style="background: url(<?php echo $this->url->get('img/product/36792756_1666732240115787_6961547340003934208_o_d0805e8bd30648dd98a4d9cf29100001_large.jpg') ?>) no-repeat;background-size: cover;background-position: center;" ></div>
					</a>
				</div>
				<div class="info">
					<h3><a href="../products/giay-z-ra-trang.html">Giày Z.Ra Trắng</a></h3>
					<div class="prices">
						<span>550,000₫</span>
						
					</div>
				</div>
			</div>
			<div class="product-item">
				<div class="img">
					<a href="../products/quan-dui-s-soda-hoa-tiet.html">
						<div class="img-show" style="background: url(<?php echo $this->url->get('img/product/37110391_1680450415410636_6887274053942378496_o_large.jpg') ?>) no-repeat;background-size: cover;background-position: center;" ></div>
					</a>
				</div>
				<div class="info">
					<h3><a href="../products/quan-dui-s-soda-hoa-tiet.html">Quần Đùi S.soda Họa Tiết</a></h3>
					<div class="prices">
						<span>320,000₫</span>
						
					</div>
				</div>
			</div>						
		</div>
		<div class="paginate text-center">
			<div id="pagination">
				<a class="page-node" href="all2679.html?page=1"><span><i class="fa fa-angle-left"></i></span></a>
				<a class="page-node" href="all2679.html?page=1">1</a>
				<span class="page-node current">2</span>
				<a class="page-node" href="all9ba9.html?page=3">3</a>
				<a class="page-node" href="allfdb0?page=4">4</a>
				<span class="page-node ">&hellip;</span>
				<a class="page-node" href="all3c09?page=22">22</a>
				<a class="page-node" href="all9ba9.html?page=3"><span><i class="fa fa-angle-right"></i></span></a>
			</div>
		</div>
	</div>
	</div>
</div>
</div>