<div id="collection">
	<!-- Begin collection info -->
	<!-- Content-->
	<div class="fix-breadcrumb " >
		<ol class="breadcrumb breadcrumb-arrow hidden-sm hidden-xs">
			<li><a href="<?= $this->url->get('') ?>" target="_self">Trang chủ</a></li>
			<li class="active"><span>SẢN PHẨM MỚI</span></li>
		</ol>
	</div>
	<div class="container">
		
		<div class="row clearfix collection-top">
			<div class="collection-left">
				<h1>SẢN PHẨM MỚI</h1>
				<div class="description">
					<img src="<?php echo $this->url->get('img/collection/sh_web_contact_cuahang-03.png') ?>" alt="SẢN PHẨM MỚI" />
				</div>
			</div>
			<div class="collection-img hidden-xs">
				<div class="img" style="background: url(<?php echo $this->url->get('img/file/banner_website-01.png') ?>) no-repeat;background-size: cover;background-position: center;" ></div>
			</div>
		</div>
	</div>
</div>