<div id="blogs">
	<div class="container">
		<div class="fix-breadcrumb " >
			<ol class="breadcrumb breadcrumb-arrow hidden-sm hidden-xs">
				<li><a href="/" target="_self">Trang chủ</a></li>
				<li class="active"><span>Hướng dẫn lựa size</span></li>
			</ol>
		</div>
		<div class="row">
			<div class="main-title2 text-center mb30">
				<h1>Hướng dẫn lựa size</h1>
			</div>
			<div class="size-list clearfix mb30">
				<div class="size-intro" >
					<div class="img">
						<a href="/blogs/huong-dan-lua-size/ao-so-mi">
							<div class="img-show" style="background: url('<?= $this->url->get('img/article/hdls-10_large.png') ?>') no-repeat;background-size: cover;background-position: center;">
							</div>
						</a>
					</div>
					<div class="article-info">
						<p>Hướng dẫn lựa size</p>
						<h3><a href="/blogs/huong-dan-lua-size/ao-so-mi">ÁO SƠ MI</a></h3>
					</div>
				</div>
				<div class="size-intro" >
					<div class="img">
						<a href="/blogs/huong-dan-lua-size/ao-polo">
							<div class="img-show" style="background: url('<?= $this->url->get('img/article/hdls-09_large.png') ?>') no-repeat;background-size: cover;background-position: center;">
							</div>
						</a>
					</div>
					<div class="article-info">
						<p>Hướng dẫn lựa size</p>
						<h3><a href="/blogs/huong-dan-lua-size/ao-polo">ÁO POLO</a></h3>
					</div>
				</div>
				<div class="size-intro" >
					<div class="img">
						<a href="/blogs/huong-dan-lua-size/ao-thun">
							<div class="img-show" style="background: url('<?= $this->url->get('img/article/hdls-08_large.png') ?>') no-repeat;background-size: cover;background-position: center;">
							</div>
						</a>
					</div>
					<div class="article-info">
						<p>Hướng dẫn lựa size</p>
						<h3><a href="/blogs/huong-dan-lua-size/ao-thun">ÁO THUN</a></h3>
					</div>
				</div>
				<div class="size-intro" >
					<div class="img">
						<a href="/blogs/huong-dan-lua-size/hoodies">
							<div class="img-show" style="background: url('<?= $this->url->get('img/article/hdls-07_large.png') ?>') no-repeat;background-size: cover;background-position: center;">
							</div>
						</a>
					</div>
					<div class="article-info">
						<p>Hướng dẫn lựa size</p>
						<h3><a href="/blogs/huong-dan-lua-size/hoodies">HOODIES</a></h3>
					</div>
				</div>
				<div class="size-intro" >
					<div class="img">
						<a href="/blogs/huong-dan-lua-size/ni-len">
							<div class="img-show" style="background: url('<?= $this->url->get('img/article/hdls-06_large.png') ?>') no-repeat;background-size: cover;background-position: center;">
							</div>
						</a>
					</div>
					<div class="article-info">
						<p>Hướng dẫn lựa size</p>
						<h3><a href="/blogs/huong-dan-lua-size/ni-len">NỈ, LEN</a></h3>
					</div>
				</div>
				<div class="size-intro" >
					<div class="img">
						<a href="/blogs/huong-dan-lua-size/ao-khoac">
							<div class="img-show" style="background: url('<?= $this->url->get('img/article/hdls-05_large.png') ?>') no-repeat;background-size: cover;background-position: center;">
							</div>
						</a>
					</div>
					<div class="article-info">
						<p>Hướng dẫn lựa size</p>
						<h3><a href="/blogs/huong-dan-lua-size/ao-khoac">ÁO KHOÁC</a></h3>
					</div>
				</div>
				<div class="size-intro" >
					<div class="img">
						<a href="/blogs/huong-dan-lua-size/boxer-underwear">
							<div class="img-show" style="background: url('<?= $this->url->get('img/article/sh_web_contact_huongdan-18_large.png') ?>') no-repeat;background-size: cover;background-position: center;">
							</div>
						</a>
					</div>
					<div class="article-info">
						<p>Hướng dẫn lựa size</p>
						<h3><a href="/blogs/huong-dan-lua-size/boxer-underwear">BOXER UNDERWEAR</a></h3>
					</div>
				</div>
				<div class="size-intro" >
					<div class="img">
						<a href="/blogs/huong-dan-lua-size/quan-dui">
							<div class="img-show" style="background: url('<?= $this->url->get('img/article/hdls-03_large.png') ?>') no-repeat;background-size: cover;background-position: center;">
							</div>
						</a>
					</div>
					<div class="article-info">
						<p>Hướng dẫn lựa size</p>
						<h3><a href="/blogs/huong-dan-lua-size/quan-dui">QUẦN ĐÙI</a></h3>
					</div>
				</div>
				<div class="size-intro" >
					<div class="img">
						<a href="/blogs/huong-dan-lua-size/jogger">
							<div class="img-show" style="background: url('<?= $this->url->get('img/article/hdls-02_large.png') ?>') no-repeat;background-size: cover;background-position: center;">
							</div>
						</a>
					</div>
					<div class="article-info">
						<p>Hướng dẫn lựa size</p>
						<h3><a href="/blogs/huong-dan-lua-size/jogger">JOGGER</a></h3>
					</div>
				</div>
				<div class="size-intro" >
					<div class="img">
						<a href="/blogs/huong-dan-lua-size/quan-kaki">
							<div class="img-show" style="background: url('<?= $this->url->get('img/article/quan-kaki_large.jpg') ?>') no-repeat;background-size: cover;background-position: center;">
							</div>
						</a>
					</div>
					<div class="article-info">
						<p>Hướng dẫn lựa size</p>
						<h3><a href="/blogs/huong-dan-lua-size/quan-kaki">Quần kaki</a></h3>
					</div>
				</div>
				<div class="size-intro" >
					<div class="img">
						<a href="/blogs/huong-dan-lua-size/quan-jean">
							<div class="img-show" style="background: url('<?= $this->url->get('img/article/quan-jean_large.jpg') ?>') no-repeat;background-size: cover;background-position: center;">
							</div>
						</a>
					</div>
					<div class="article-info">
						<p>Hướng dẫn lựa size</p>
						<h3><a href="/blogs/huong-dan-lua-size/quan-jean">Quần Jean</a></h3>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>