<nav class="sidebar sidebar-offcanvas" id="sidebar">
  <ul class="nav">
    <li class="nav-item nav-profile">
      <div class="nav-link">
        <div class="user-wrapper">
          <div class="profile-image">
            <img src="<?= $this->url->get('ad/images/faces/face1.jpg') ?>" alt="profile image">
          </div>
          <div class="text-wrapper">
            <p class="profile-name"><?php if ($this->session->has('admin')) {
              echo $this->session->get('admin');
            } ?></p>
            <div>
              <small class="designation text-muted">Manager</small>
              <span class="status-indicator online"></span>
            </div>
          </div>
        </div>
       <!--  <button class="btn btn-success btn-block">New Project
          <i class="mdi mdi-plus"></i>
        </button> -->
      </div>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="<?php echo $this->url->get('backend') ?>">
        <i class="menu-icon mdi mdi-television"></i>
        <span class="menu-title">Dashboard</span>
      </a>
    </li>

    <!-- Quản lý đơn hàng -->
    <li class="nav-item">
      <a class="nav-link" data-toggle="collapse" href="#bill" aria-expanded="false" aria-controls="bill">
        <i class="menu-icon mdi mdi-clipboard-text"></i>
        <span class="menu-title">Quản lý đơn hàng</span>
        <i class="menu-arrow"></i>
      </a>
      <div class="collapse" id="bill">
        <ul class="nav flex-column sub-menu">
          <li class="nav-item">
            <a class="nav-link" href="">Đơn hàng</a>
          </li>
        </ul>
      </div>
    </li>

    <!-- Quản lý sản phẩm -->
    <li class="nav-item">
      <a class="nav-link" data-toggle="collapse" href="#product" aria-expanded="false" aria-controls="product">
        <i class="menu-icon mdi mdi-cup-water"></i>
        <span class="menu-title">Quản lý sản phẩm</span>
        <i class="menu-arrow"></i>
      </a>
      <div class="collapse" id="product">
        <ul class="nav flex-column sub-menu">
          <li class="nav-item">
            <a class="nav-link" href="<?= $this->url->get('backend/products') ?>">Sản phẩm</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<?= $this->url->get('backend/categories') ?>">Danh mục sản phẩm</a>
          </li>
        </ul>
      </div>
    </li>

    <!-- Quản lý khách hàng -->
    <li class="nav-item">
      <a class="nav-link" data-toggle="collapse" href="#customer" aria-expanded="false" aria-controls="customer">
        <i class="menu-icon mdi mdi-account-multiple-outline"></i>
        <span class="menu-title">Quản lý khách hàng</span>
        <i class="menu-arrow"></i>
      </a>
      <div class="collapse" id="customer">
        <ul class="nav flex-column sub-menu">
          <li class="nav-item">
            <a class="nav-link" href="<?php echo $this->url->get('backend/users') ?>">Khách hàng</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Messages</a>
          </li>
        </ul>
      </div>
    </li>

    <!-- Quản lý bài viết -->
    <li class="nav-item">
      <a class="nav-link" data-toggle="collapse" href="#news" aria-expanded="false" aria-controls="news">
        <i class="menu-icon mdi mdi-newspaper"></i>
        <span class="menu-title">Quản lý bài viết</span>
        <i class="menu-arrow"></i>
      </a>
      <div class="collapse" id="news">
        <ul class="nav flex-column sub-menu">
          <li class="nav-item">
            <a class="nav-link" href="">Bài viết</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Danh mục bài viết</a>
          </li>
        </ul>
      </div>
    </li>
    
    <!-- Quản lý admin -->
    <li class="nav-item">
      <a class="nav-link" href="<?php echo $this->url->get('backend/admin') ?>">
        <i class="menu-icon mdi mdi-account-circle"></i>
        <span class="menu-title">Admin</span>
      </a>
    </li>

    <!-- Setting -->
    <li class="nav-item">
      <a class="nav-link" href="<?php echo $this->url->get('backend/setting') ?>">
        <i class="menu-icon mdi mdi-settings"></i>
        <span class="menu-title">Setting</span>
      </a>
    </li>
  </ul>
</nav>