<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en" class="flexbox">
  <head>
    <link rel="shortcut icon" href="//theme.hstatic.net/1000026602/1000381372/14/favicon.png?v=72" type="image/png" />
    <title>
      SomeHow Store - Thanh toán đơn hàng
    </title>
    <meta name="description" content="SomeHow Store - Thanh to&#225;n đơn h&#224;ng" />
    <link href='//hstatic.net/0/0/global/checkouts.css?v=1.1' rel='stylesheet' type='text/css'  media='all'  />
    <link href='//theme.hstatic.net/1000026602/1000381372/14/check_out.css?v=72' rel='stylesheet' type='text/css'  media='all'  />
    <script src='//hstatic.net/0/0/global/jquery.min.js' type='text/javascript'></script>
    <script src='//hstatic.net/0/0/global/jquery.validate.js' type='text/javascript'></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=2, user-scalable=no">
    <script type="text/javascript" src="<?= $this->url->get('js/checkout.js') ?>"></script>
    <script type = "text/javascript" >
      var toggleShowOrderSummary = false;
      $(document).ready(function() {
      var currentUrl = '';


      currentUrl = '/checkouts/7e4981d245d94b1ab0bfa41f6276dadd?step=1';


      if ($('#reloadValue').val().length == 0) {
          $('#reloadValue').val(currentUrl);
          $('body').show();
      } else {
          window.location = $('#reloadValue').val();
          $('#reloadValue').val('');
      }

      $('body')
          .on('click', '.order-summary-toggle', function() {
              toggleShowOrderSummary = !toggleShowOrderSummary;

              if (toggleShowOrderSummary) {
                  $('.order-summary-toggle')
                      .removeClass('order-summary-toggle-hide')
                      .addClass('order-summary-toggle-show');

                  $('.sidebar:not(".sidebar-second") .sidebar-content .order-summary')
                      .removeClass('order-summary-is-collapsed')
                      .addClass('order-summary-is-expanded');

                  $('.sidebar.sidebar-second .sidebar-content .order-summary')
                      .removeClass('order-summary-is-expanded')
                      .addClass('order-summary-is-collapsed');
              } else {
                  $('.order-summary-toggle')
                      .removeClass('order-summary-toggle-show')
                      .addClass('order-summary-toggle-hide');

                  $('.sidebar:not(".sidebar-second") .sidebar-content .order-summary')
                      .removeClass('order-summary-is-expanded')
                      .addClass('order-summary-is-collapsed');

                  $('.sidebar.sidebar-second .sidebar-content .order-summary')
                      .removeClass('order-summary-is-collapsed')
                      .addClass('order-summary-is-expanded');
              }
          });
        });
    </script>
    <meta name="google-site-verification" content="ksL-fQf3EO-xA1-NpwDXo-VW-BMIxnSgH5DZxv88Twk" />
    <noscript><img height='1' width='1' style='display:none' src ='https://www.facebook.com/tr?id=235758736796649&amp;ev=PageView&amp;noscript=1'/></noscript>
  </head>
  <body>
    <?php $total_price = $cart->getTotal() ?>
    <div class="content">
      <div class="wrap">
        <div class="sidebar">
          <div class="sidebar-content">
            <div class="order-summary order-summary-is-collapsed">
              <h2 class="visually-hidden">Thông tin đơn hàng</h2>
              <div class="order-summary-sections">
                <div class="order-summary-section order-summary-section-product-list" data-order-summary-section="line-items">
                  <table class="product-table">
                    <thead>
                      <tr>
                        <th scope="col"><span class="visually-hidden">Hình ảnh</span></th>
                        <th scope="col"><span class="visually-hidden">Mô tả</span></th>
                        <th scope="col"><span class="visually-hidden">Số lượng</span></th>
                        <th scope="col"><span class="visually-hidden">Giá</span></th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php foreach ($cart->getContent() as $cart) : ?>
                      <tr class="product" data-product-id="1016466982" data-variant-id="1031385033">
                        <td class="product-image">
                          <div class="product-thumbnail">
                            <div class="product-thumbnail-wrapper">
                              <img class="product-thumbnail-image" alt="Áo Khoác Ni.ke Đen Phối" src="<?= $this->url->get('img/product/'.$cart['img']) ?>" />
                            </div>
                            <span class="product-thumbnail-quantity" aria-hidden="true"><?= $cart['qty'] ?></span>
                          </div>
                        </td>
                        <td class="product-description">
                          <span class="product-description-name order-summary-emphasis"><?= $cart['name'] ?></span>
                          <span class="product-description-variant order-summary-small-text">
                          <?= $cart['color'] . ' / ' . $cart['size']  ?>
                          </span>
                        </td>
                        <td class="product-quantity visually-hidden"><?= $cart['qty'] ?></td>
                        <td class="product-price">
                          <span class="order-summary-emphasis"><?= number_format($cart['total']) ?>₫</span>
                        </td>
                      </tr>
                      <?php endforeach; ?>
                    </tbody>
                  </table>
                </div>
                <div class="order-summary-section order-summary-section-total-lines" data-order-summary-section="payment-lines">
                  <table class="total-line-table">
                    <thead>
                      <tr>
                        <th scope="col"><span class="visually-hidden">Mô tả</span></th>
                        <th scope="col"><span class="visually-hidden">Giá</span></th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr class="total-line total-line-subtotal">
                        <td class="total-line-name">Tạm tính</td>
                        <td class="total-line-price">
                          <span class="order-summary-emphasis" data-checkout-subtotal-price-target="<?php echo '' ?>">
                         <?php echo $total_price ?>₫
                          </span>
                        </td>
                      </tr>
                      <tr class="total-line total-line-shipping">
                        <td class="total-line-name">Phí vận chuyển</td>
                        <td class="total-line-price">
                          <span class="order-summary-emphasis" data-checkout-total-shipping-target="0">
                          —
                          </span>
                        </td>
                      </tr>
                    </tbody>
                    <tfoot class="total-line-table-footer">
                      <tr class="total-line">
                        <td class="total-line-name payment-due-label">
                          <span class="payment-due-label-total">Tổng cộng</span>
                        </td>
                        <td class="total-line-name payment-due">
                          <span class="payment-due-currency">VND</span>
                          <span class="payment-due-price" data-checkout-payment-due-target="147000000">
                          1,470,000₫
                          </span>
                        </td>
                      </tr>
                    </tfoot>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="main">
          <div class="main-header">
            <a href="<?= $this->url->get('') ?>" class="logo">
              <h1 class="logo-text">SomeHow Store</h1>
            </a>
            <ul class="breadcrumb">
              <li class="breadcrumb-item">
                <a href="<?= $this->url->get('frontend/cart') ?>">Giỏ hàng</a>
              </li>
              <li class="breadcrumb-item breadcrumb-item-current">
                Thông tin giao hàng
              </li>
            </ul>
          </div>
          <div class="main-content">
            <div class="step">
              <div class="step-sections steps-onepage" step="1">
                <div class="section">
                  <div class="section-header">
                    <h2 class="section-title">Thông tin giao hàng</h2>
                  </div>
                  <div class="section-content section-customer-information ">
                    <p class="section-content-text">
                      Bạn đã có tài khoản?
                      <a href="/account/login?urlredirect=%2Fcheckouts%2F7e4981d245d94b1ab0bfa41f6276dadd%3Fstep%3D1">Đăng nhập</a>
                    </p>
                    <div class="fieldset">
                      <div class="field field-required  ">
                        <div class="field-input-wrapper">
                          <label class="field-label" for="billing_address_full_name">Họ và tên</label>
                          <input placeholder="Họ và tên" autocapitalize="off" spellcheck="false" class="field-input" size="30" type="text" id="billing_address_full_name" name="billing_address[full_name]" value="" />
                        </div>
                      </div>
                      <div class="field  field-two-thirds  ">
                        <div class="field-input-wrapper">
                          <label class="field-label" for="checkout_user_email">Email</label>
                          <input placeholder="Email" autocapitalize="off" spellcheck="false" class="field-input" size="30" type="email" id="checkout_user_email" name="checkout_user[email]" value="" />
                        </div>
                      </div>
                      <div class="field field-required field-third  ">
                        <div class="field-input-wrapper">
                          <label class="field-label" for="billing_address_phone">Số điện thoại</label>
                          <input placeholder="Số điện thoại" autocapitalize="off" spellcheck="false" class="field-input" size="30" maxlength="11" type="tel" id="billing_address_phone" name="billing_address[phone]" value="" />
                        </div>
                      </div>
                      <div class="field field-required  ">
                        <div class="field-input-wrapper">
                          <label class="field-label" for="billing_address_address1">Địa chỉ</label>
                          <input placeholder="Địa chỉ" autocapitalize="off" spellcheck="false" class="field-input" size="30" type="text" id="billing_address_address1" name="billing_address[address1]" value="" />
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="section-content">
                    <div class="fieldset">
                      <form id="form_update_shipping_method" class="field" accept-charset="UTF-8" method="post">
                        <input name="utf8" type="hidden" value="✓">
                        <div class="content-box mt0">
                          <div class="radio-wrapper content-box-row">
                            <label class="radio-label">
                              <div class="radio-input">
                                <input type="radio" id="customer_pick_at_location_false" name="customer_pick_at_location" class="input-radio" value="false" checked>
                              </div>
                              <span class="radio-label-primary">Giao tận nơi</span>
                            </label>
                          </div>
                          <div id="form_update_location_customer_shipping" class="radio-wrapper content-box-row content-box-row-padding content-box-row-secondary " for="customer_pick_at_location_false">
                            <input name="utf8" type="hidden" value="✓">
                            <div class="field field-show-floating-label  field-half ">
                              <div class="field-input-wrapper field-input-wrapper-select">
                                <label class="field-label" for="customer_shipping_province"> Tỉnh / thành  </label>
                                <select class="field-input" id="customer_shipping_province" name="customer_shipping_province">
                                  <option data-code="null" value="null" selected>  Chọn tỉnh / thành </option>
                                  <option data-code="HC" value="50" >Hồ Chí Minh</option>
                                  <option data-code="HI" value="1" >Hà Nội</option>
                                  <option data-code="DA" value="32" >Đà Nẵng</option>
                                  <option data-code="AG" value="57" >An Giang</option>
                                  <option data-code="BV" value="49" >Bà Rịa - Vũng Tàu</option>
                                  <option data-code="BG" value="15" >Bắc Giang</option>
                                  <option data-code="BK" value="4" >Bắc Kạn</option>
                                  <option data-code="BL" value="62" >Bạc Liêu</option>
                                  <option data-code="BN" value="18" >Bắc Ninh</option>
                                  <option data-code="BT" value="53" >Bến Tre</option>
                                  <option data-code="BD" value="35" >Bình Định</option>
                                  <option data-code="BI" value="47" >Bình Dương</option>
                                  <option data-code="BP" value="45" >Bình Phước</option>
                                  <option data-code="BU" value="39" >Bình Thuận</option>
                                  <option data-code="CM" value="63" >Cà Mau</option>
                                  <option data-code="CN" value="59" >Cần Thơ</option>
                                  <option data-code="CB" value="3" >Cao Bằng</option>
                                  <option data-code="DC" value="42" >Đắk Lắk</option>
                                  <option data-code="DO" value="43" >Đắk Nông</option>
                                  <option data-code="DB" value="7" >Điện Biên</option>
                                  <option data-code="DN" value="48" >Đồng Nai</option>
                                  <option data-code="DT" value="56" >Đồng Tháp</option>
                                  <option data-code="GL" value="41" >Gia Lai</option>
                                  <option data-code="HG" value="2" >Hà Giang</option>
                                  <option data-code="HM" value="23" >Hà Nam</option>
                                  <option data-code="HT" value="28" >Hà Tĩnh</option>
                                  <option data-code="HD" value="19" >Hải Dương</option>
                                  <option data-code="HP" value="20" >Hải Phòng</option>
                                  <option data-code="HU" value="60" >Hậu Giang</option>
                                  <option data-code="HO" value="11" >Hòa Bình</option>
                                  <option data-code="HY" value="21" >Hưng Yên</option>
                                  <option data-code="KH" value="37" >Khánh Hòa</option>
                                  <option data-code="KG" value="58" >Kiên Giang</option>
                                  <option data-code="KT" value="40" >Kon Tum</option>
                                  <option data-code="LI" value="8" >Lai Châu</option>
                                  <option data-code="LD" value="44" >Lâm Đồng</option>
                                  <option data-code="LS" value="13" >Lạng Sơn</option>
                                  <option data-code="LO" value="6" >Lào Cai</option>
                                  <option data-code="LA" value="51" >Long An</option>
                                  <option data-code="ND" value="24" >Nam Định</option>
                                  <option data-code="NA" value="27" >Nghệ An</option>
                                  <option data-code="NB" value="25" >Ninh Bình</option>
                                  <option data-code="NT" value="38" >Ninh Thuận</option>
                                  <option data-code="PT" value="16" >Phú Thọ</option>
                                  <option data-code="PY" value="36" >Phú Yên</option>
                                  <option data-code="QB" value="29" >Quảng Bình</option>
                                  <option data-code="QM" value="33" >Quảng Nam</option>
                                  <option data-code="QG" value="34" >Quảng Ngãi</option>
                                  <option data-code="QN" value="14" >Quảng Ninh</option>
                                  <option data-code="QT" value="30" >Quảng Trị</option>
                                  <option data-code="ST" value="61" >Sóc Trăng</option>
                                  <option data-code="SL" value="9" >Sơn La</option>
                                  <option data-code="TN" value="46" >Tây Ninh</option>
                                  <option data-code="TB" value="22" >Thái Bình</option>
                                  <option data-code="TY" value="12" >Thái Nguyên</option>
                                  <option data-code="TH" value="26" >Thanh Hóa</option>
                                  <option data-code="TT" value="31" >Thừa Thiên Huế</option>
                                  <option data-code="TG" value="52" >Tiền Giang</option>
                                  <option data-code="TV" value="54" >Trà Vinh</option>
                                  <option data-code="TQ" value="5" >Tuyên Quang</option>
                                  <option data-code="VL" value="55" >Vĩnh Long</option>
                                  <option data-code="VT" value="17" >Vĩnh Phúc</option>
                                  <option data-code="YB" value="10" >Yên Bái</option>
                                </select>
                              </div>
                            </div>
                            <div class="field field-show-floating-label  field-half ">
                              <div class="field-input-wrapper field-input-wrapper-select">
                                <label class="field-label" for="customer_shipping_district">Quận / huyện</label>
                                <select class="field-input" id="customer_shipping_district" name="customer_shipping_district">
                                  <option data-code="null" value="null" selected>Chọn quận / huyện</option>
                                </select>
                              </div>
                            </div>
                          </div>
                        </div>
                      </form>
                    </div>
                    <div class="section-content section-customer-information fieldset" id="div_country_not_vietnam">
                      <div class="field field-two-thirds">
                        <div class="field-input-wrapper">
                          <label class="field-label" for="billing_address_city">Thành phố</label>
                          <input placeholder="Thành phố" autocapitalize="off" spellcheck="false" class="field-input" size="30" type="text" id="billing_address_city" name="billing_address[city]" value="" />
                        </div>
                      </div>
                      <div class="field field-third">
                        <div class="field-input-wrapper">
                          <label class="field-label" for="billing_address_zip">Mã bưu chính</label>
                          <input placeholder="Mã bưu chính" autocapitalize="off" spellcheck="false" class="field-input" size="30" type="text" id="billing_address_zip" name="billing_address[zip]" value="" />
                        </div>
                      </div>
                    </div>
                  </div>
                  <div id="change_pick_location_or_shipping">
                    <div class="inventory_location">
                    </div>
                    <div id="section-shipping-rate">
                      <div class="section-header">
                        <h2 class="section-title">Phương thức vận chuyển</h2>
                      </div>
                      <div class="section-content">
                        <div class="content-box  blank-slate">
                          <i class="blank-slate-icon icon icon-closed-box "></i>
                          <p>Vui lòng chọn tỉnh / thành để có danh sách phương thức vận chuyển.</p>
                        </div>
                      </div>
                    </div>
                    <div id="section-payment-method" class="section">
                      <div class="section-header">
                        <h2 class="section-title">Phương thức thanh toán</h2>
                      </div>
                      <div class="section-content">
                        <div class="content-box">
                          <div class="radio-wrapper content-box-row">
                            <label class="radio-label" for="payment_method_id_54463">
                              <div class="radio-input">
                                <input id="payment_method_id_54463" class="input-radio" name="payment_method_id" type="radio" value="54463" checked />
                              </div>
                              <span class="radio-label-primary">Thanh toán khi giao hàng (COD)</span>
                            </label>
                          </div>
                          <div class="radio-wrapper content-box-row content-box-row-secondary " for="payment_method_id_54463">
                            <div class="blank-slate">
                              - Miễn phí ship đối với đơn hàng nội thành HCM.
                              - Miễn phí ship ở các tỉnh với đơn hàng trên 500.000 đ.
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="step-footer">
                <form id="form_next_step" accept-charset="UTF-8" method="post">
                  <input name="utf8" type="hidden" value="✓">
                  <button type="submit" class="step-footer-continue-btn btn">
                  <span class="btn-content">Hoàn tất đơn hàng</span>
                  <i class="btn-spinner icon icon-button-spinner"></i>
                  </button>
                </form>
                <a class="step-footer-previous-link" href="<?= $this->url->get('frontend/cart') ?>">
                  <svg class="previous-link-icon icon-chevron icon" xmlns="http://www.w3.org/2000/svg" width="6.7" height="11.3" viewBox="0 0 6.7 11.3">
                    <path d="M6.7 1.1l-1-1.1-4.6 4.6-1.1 1.1 1.1 1 4.6 4.6 1-1-4.6-4.6z"></path>
                  </svg>
                  Giỏ hàng
                </a>
              </div>
            </div>
          </div>
          <div class="main-footer">
          </div>
        </div>
      </div>
    </div>
  </body>
</html>