<div id="layout-page" class="pd40">
	<div  class="container">
		<div class="main-title2 text-center mb30">
			<h1>Tài khoản của bạn <a class="logout" href="<?= $this->url->get('frontend/account/logout') ?>"><span class="fa fa-sign-out"></span>Thoát</a></h1>
		</div>
		<div id="customer_orders" class="col-xs-12">
			<p>Bạn chưa đặt mua sản phẩm.</p>
		</div>
		<div class="col-xs-12" id="customer_sidebar">
			<h2>Vinh Phan</h2>
			<p class="email ">kiepvozanh11@gmail.com</p>
			<div class="address ">
				<p></p>
				<p></p>
				<p> </p>
				<p></p>
				<a id="view_address" href="/account/addresses">Xem địa chỉ</a>
			</div>
		</div>
	</div>
</div>