<div id="cart">
	<div class="fix-breadcrumb " >
	<ol class="breadcrumb breadcrumb-arrow hidden-sm hidden-xs">
		<li><a href="/" target="_self">Trang chủ</a></li>
		<li class="active">Giỏ hàng: <span id="ajax-breadcrumb-cart-item-count">0</span>
			<span id="ajax-breadcrumb-cart-item-text">sản phẩm</span> -
			<span id="ajax-breadcrumb-cart-total-price">0₫</span></li>
	</ol>
</div>
<div class="container">
	<!-- Begin empty cart -->
	<div class="row" >
		<div id="layout-page" class="col-md-12">
			<div class="main-title2 mb30">
				<h1>Giỏ hàng</h1>
			</div>
			<p class="text-center">
				Không có sản phẩm nào trong giỏ hàng!</p>
			<p class="text-center"><a  href="/collections/all">
				<i class="fa fa-reply"></i> Tiếp tục mua hàng</a>
			</p>
		</div>
	</div>
	<!-- End empty cart -->
	<!-- Begin cart -->
</div>
<link rel="stylesheet" href="<?php echo $this->url->get('css/cart.css') ?>">