<div class="content-wrapper">
  <div class="row">
    <div class="col-12 grid-margin">
      <div class="card">
        <div class="card-body">
          <?php $this->flashSession->output() ?>
          <h4 class="card-title""><b>Cài đặt địa chỉ cửa hàng</b></h4>
          <hr>
          <form class="form-sample" method="post" enctype="multipart/form-data">
            <p class="card-description">
             
            </p>
            <?php $count = 0; foreach ($setting->info as $info) : ?>
            <div class="row">
              <div class="col-md-6">
                  <div class="form-group row">
                  <label class="col-sm-3 col-form-label">Địa chỉ <?= $count+1 ?>:</label>
                  <div class="col-sm-9">
                    <input type="text" class="form-control" name="address[]" placeholder="" value="<?php echo $info['address'] ?>">
                  </div>
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group row">
                  <label class="col-sm-3 col-form-label">Điện thoại</label>
                  <div class="col-sm-9">
                    <input type="text" class="form-control" name="phone[]" placeholder="" value="<?php echo $info['phone'] ?>">
                  </div>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6">
                  <div class="form-group row">
                  <label class="col-sm-3 col-form-label"></label>
                  <div class="col-sm-9">
                    <input type="file" class="form-control" name="images<?= $count ?>" placeholder="">
                  </div>
                </div>
              </div>
              <div class="col-md-6">
                  <div class="form-group row">
                    <label class="col-sm-3 col-form-label"><img src="<?= $this->url->get('img/14/'.$info['images']) ?>" alt="" height="40px"></label>
                      
                  </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                  <div class="form-group row">
                  <label class="col-sm-1 col-form-label">Maps:</label>
                  <div class="col-sm-8" style="margin-left: 40px">
                    <textarea class="form-control" name="maps[]" width="100%"><?= $info['maps'] ?></textarea>
                  </div>
                  </div>
              </div>
            </div>
            <hr>
            <?php $count += 1; endforeach; ?>
            <hr>
            <button class="btn btn-primary" style="color: white">
              <i class="mdi mdi-settings"></i>Cập nhật địa chỉ</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>