<div class="content-wrapper">
  <div class="row">
    <div class="col-12 grid-margin">
      <div class="card">
        <div class="card-body">
          <?php $this->flashSession->output() ?>
          <h4 class="card-title""><b>Cài đặt logo</b></h4>
          <hr>
          <form class="form-sample" method="post" enctype="multipart/form-data">
            <p class="card-description">
            </p>
            <div class="row">
              <div class="col-md-6">
                  <div class="form-group row">
                  <label class="col-sm-3 col-form-label">Web thumbnail</label>
                  <div class="col-sm-9">
                    <input type="file" class="form-control" name="web_thumbnail" placeholder="">
                  </div>
                </div>
              </div>
              <div class="col-md-6">
                  <div class="form-group row">
                  <label class="col-sm-3 col-form-label"><img src="<?= $this->url->get('img/14/'.$setting->web_thumbnail) ?>" alt="" width="20px"></label>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6">
                  <div class="form-group row">
                  <label class="col-sm-3 col-form-label">Web logo</label>
                  <div class="col-sm-9">
                    <input type="file" class="form-control" name="web_logo" placeholder="">
                  </div>
                </div>
              </div>
              <div class="col-md-6">
                  <div class="form-group row">
                  <label class="col-sm-3 col-form-label"><img src="<?= $this->url->get('img/14/'.$setting->web_logo) ?>" alt="" width="30px"></label>
                </div>
              </div>
            </div>
            <hr>
            <button class="btn btn-primary" style="color: white">
              <i class="mdi mdi-settings"></i>Cập nhật logo</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>