<div class="page pb30">
	<div class="container">
		<div class="fix-breadcrumb " >
		<ol class="breadcrumb breadcrumb-arrow hidden-sm hidden-xs">
			<li><a href="<?= $this->url->get('') ?>" target="_self">Trang chủ</a></li>
			<li class="active"><span>Hướng Dẫn Mua Hàng Online</span></li>
		</ol>
		</div>
		<div id="layout-page">
			<div class="main-title2 text-center">
				<h1>Hướng Dẫn Mua Hàng Online</h1>
			</div>
			<div class="content-page">
				<p><strong></strong><br></p><p><strong>Bước 1:</strong> 
					<span>&nbsp;Bạn có thể truy cập vào website Somehow.vn và&nbsp;</span>
					<span>Chọn từng danh mục sản phẩm để tìm kiếm.</span></p><p><img src="<?php echo $this->url->get('img/file/6.jpg') ?>" data-mce-src="//file.hstatic.net/1000026602/file/6.jpg"></p><p>
					<span></span><br></p><p>
					<span><strong>Bước 2:</strong> Sau khi chọn được nhóm sản phẩm cần mua, bạn có thể tìm kiếm sản phẩm mình cần một cách nhanh chóng. (Ví dụ: Vào nhóm áo thun, tìm áo thun trơn tay ngắn cổ tròn. Đầu tiên chọn danh mục áo thun, và bấm vào phần lọc theo để tìm kiếm như hình dưới)</span></p><p><img src="<?php echo $this->url->get('img/file/7.jpg') ?>" data-mce-src="//file.hstatic.net/1000026602/file/7.jpg"></p><p>
					<span></span><br></p><p>
					<span><strong>Bước 3:</strong> Sau khi đã chọn được sản phẩm cần mua, bạn chọn nút thêm sản phẩm vào giỏ hàng - nếu bạn muốn tìm và mua thêm sản phẩm khác. </span></p><p>
					<span>Sau khi đã thêm vào giỏ hàng đầy đủ các sản phẩm bạn muốn mua. Hãy click vào icon giỏ hàng để kiểm tra đơn hàng.</span>
					<span></span></p><p><img src="<?php echo $this->url->get('img/file/8.jpg') ?>" data-mce-src="//file.hstatic.net/1000026602/file/8.jpg"></p><p><strong>Bước 4:</strong> Ở trang giỏ hàng, bạn có thể điều chỉnh số lượng sản phẩm hoặc xóa sản phẩm nếu không thích nữa. Sau khi đã kiểm tra xong, bấm vào nút thanh toán và điền đầy đủ thông tin cá nhân.
					<span></span></p><p>
					<img src="<?php echo $this->url->get('img/file/9.jpg') ?>" data-mce-src="//file.hstatic.net/1000026602/file/9.jpg"></p><p><br></p><p style="text-align: justify;" data-mce-style="text-align: justify;"><em>* Bạn cần nhập đầy đủ và chính xác thông tin để hàng có thể được giao đến đúng địa chỉ người mua hàng, tránh việc thất lạc hoặc không giao được đơn hàng đến cho bạn.</em><br></p><p>
					<img src="<?php echo $this->url->get('img/file/10.jpg') ?>" data-mce-src="//file.hstatic.net/1000026602/file/10.jpg"></p><p style="text-align: justify;" data-mce-style="text-align: justify;"><em></em><br></p><p style="text-align: justify;" data-mce-style="text-align: justify;">- Sau khi điền đầy đủ thông tin và kiểm tra lại đơn hàng, giá tiền, bạn hãy bấm vào nút&nbsp;
					<strong>HOÀN TẤT ĐƠN HÀNG</strong>.<br></p>
					<p style="text-align: justify;" data-mce-style="text-align: justify;">Nhân viên shop sẽ liên hệ với bạn qua điện thoại để xác nhận đơn hàng và thông tin giao hàng.</p>
			</div>
		</div>
	</div>
</div>