<div id="layout-page" class="bgfafafa">
	<div class="container">
		<div id="customer-login">
			<h1>Tạo tài khoản</h1>
			<div class="userbox">
				<form accept-charset='UTF-8' action='/account' id='create_customer' method='post'>
				<input name='form_type' type='hidden' value='create_customer'>
				<input name='utf8' type='hidden' value='✓'>
				<div id="last_name" class="clearfix large_form">

					<input required type="text" value="" name="customer[last_name]" placeholder="Họ" id="last_name" class="text" size="30" />

					<input required type="text" value="" name="customer[first_name]" placeholder="Tên" id="first_name" class="text" size="30" />

					<input required type="email" value="" placeholder="Email" name="customer[email]" id="email" class="text" size="30" />

					<input required type="password" value="" placeholder="Mật khẩu" name="customer[password]" id="password" class="password text" size="30" />
				</div>

				<div class="action_bottom">
					<input class="btn-more btn-login" type="submit" value="Đăng ký" />			
				</div>
				<div class="req_pass">
					<a class="btn-more btn-register" href="<?= $this->url->get('login') ?>">Quay về</a>
				</div>
				</form>
			</div>
		</div>
	</div>
</div><!-- #register -->